default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bar-crawler-development

test:
  <<: *default
  database: bar-crawler-test

production:
  <<: *default
  database: bar-crawler
