# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7352f3a98ef3299ce5b5df7faa7e1eebb930a13af56aff8bdd0896c25406867928ff63427fd6da3199f242d7e63bb0b033b36a4c3a91058b54be14722f4f9315

test:
  secret_key_base: d22f48bb863377a4bf1e5acb8e7fff0473909c51eed883b1e05f3b557056c3f20946e19e651d132e2fd744e0f8ff0512c7337cc3308d978aa59719e164056a47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
